# -*- coding: utf-8 -*-
"""GIT 01_Merge_and_Statistic_IsTheWorldReadyForTheNextPandemic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1daI8qSL4Me0vaiJkEkuY1bNmMSH5fazY

## IsTheWorldReadyForTheNextPandemic - Mini Project
### Project handled by Liza, Ravit, Hagit and Hodaya

**This notebook includes preparation of the actual base dataset which trainig model will run upon.**

Remark: Data analysis will be done per Country_code[Location_key] and not per Country_code and regional

Comment: baseline data, excluding regional or sub-national slices

---
## Part 1 · Setup, data
"""

from google.colab import drive
drive.mount('/content/drive')

import os

# בדיקה האם הקוד רץ כרגע בתוך Google Colab
if 'google.colab' in str(get_ipython()):
    # אם כן, נתחבר לדרייב ונשתמש בנתיב המלא שלך
    from google.colab import drive
    drive.mount('/content/drive')
    data_dir = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'
else:
    # אם הקוד רץ במחשב או ב-Git, נשתמש בתיקייה מקומית
    data_dir = './data/'

# Core imports.
import numpy as np
np.random.seed(42)  # For reproducibility
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set the path where your DataSet CSVs located.
data_dir = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'

# Load the standard/smaller files
country_index = pd.read_csv(data_dir + "country Index.csv")
ict_adoption = pd.read_csv(data_dir + "ict adoption by 100 people.csv")
ghs_index = pd.read_csv(data_dir + "2021-GHS-Index-April-2022.csv")
health = pd.read_csv(data_dir + "health.csv")
demographics = pd.read_csv(data_dir + "demographics.csv")
covid_daily = pd.read_csv(data_dir + "WHO-COVID-19-global-daily-data.csv")

print("Standard files loaded successfully!")

# Load the Big files - vaccinations/epidemiology
vaccinations = pd.read_csv(data_dir + "vaccinations.csv")
epidemiology = pd.read_csv(data_dir + "epidemiology.csv")

print("vaccinations/epidemiology BIG files loaded successfully!")

"""# DataSet modification, preparation for model training
The purpose of this section is to create baseline dataset tables and modify/prepare them for model traning and science query by removing unnecessary data/remove null values etc
"""

# ==================================================
# Clean country Index.csv
# ==================================================

# Clean country Index.csv tables and leave only the records with aggregation_level equal to zero
# aggregation_level=1 means a district under a country
# aggregation_level=2 means a Sub-region within a district

import os
import pandas as pd

# ==========================================
# 1. DEFINE SHARED WORKSPACE PATH
# ==========================================
data_dir = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'

input_filename = "country Index.csv"
output_filename = "Country_Ind_md.csv"

input_path = os.path.join(data_dir, input_filename)
output_path = os.path.join(data_dir, output_filename)

print("Initializing dataset modification pipeline...")

# ==========================================
# 2. UPLOAD & READ RAW SOURCE FILE
# ==========================================
if not os.path.exists(input_path):
    raise FileNotFoundError(f"❌ Error: Could not find the file at {input_path}. Please verify your Google Drive mounting and folder name.")

print(f"Reading source file: {input_filename}")
df_country = pd.read_csv(input_path)
print(f"-> Original Baseline Shape: {df_country.shape}")

# ==========================================
# 3. APPLY DATA MODIFICATION (FILTERING)
# ==========================================
print("Filtering records where aggregation_level == 0...")

# Standardize column naming just in case there are trailing spaces in the CSV header
df_country.columns = df_country.columns.str.strip()

# Create the modified slice containing only country-level rows - meaning aggregation_level is zero
df_country_md = df_country[df_country['aggregation_level'] == 0].copy()

# Removing un-necessary fields
columns_to_drop = ['subregion1_name', 'subregion2_code', 'subregion2_name']

df_country_md = df_country_md.drop(columns=[col for col in columns_to_drop if col in df_country_md.columns])

#print file
output_path = 'Country_Ind_md.csv'
df_country_md.to_csv(output_path, index=False)

print(f"3 fields were removed succesfully: {output_path}")
print(f"-> Filtered Dataset Shape: {df_country_md.shape}")

# ==========================================
# 4. CREATE NEW PHYSICAL FILE IN GOOGLE DRIVE
# ==========================================
print(f"Writing new file to Drive: {output_filename}")

# Index=False prevents Pandas from adding a redundant, unnamed sequential column to your new CSV file
df_country_md.to_csv(output_path, index=False)

print("=" * 60)
print("✅ Success! Physical file created and saved securely.")
print(f"File Location: {output_path}")
print("=" * 60)

# ==========================================
# 5. INTEGRITY VALIDATION PREVIEW
# ==========================================
print("\n--- FIRST 5 ROWS OF THE MODIFIED COUNTRY INDEX FILTRATION ---")
pd.set_option('display.max_columns', 10)
print(df_country_md.head(5))

# =======================================================================
# Merge "Country_Ind_md.csv" and "demographics.csv" per Location_key
# =======================================================================

import os
import pandas as pd

# ==========================================
# 1. DEFINE SHARED WORKSPACE PATHS
# ==========================================
data_dir = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'
country_file = "Country_Ind_md.csv"
demo_file = "demographics.csv"
output_file = "demographics_Ind_md.csv"

path_country = os.path.join(data_dir, country_file)
path_demo = os.path.join(data_dir, demo_file)
path_output = os.path.join(data_dir, output_file)

print("Initializing cross-table integration pipeline...")

# ==========================================
# 2. UPLOAD & READ BOTH FILES
# ==========================================
if not os.path.exists(path_country) or not os.path.exists(path_demo):
    raise FileNotFoundError("❌ Error: Missing source files. Please ensure both 'Country_Ind_md.csv' and 'demographics.csv' are present in the directory.")

print(f"Reading: {country_file}")
df_country_md = pd.read_csv(path_country)

print(f"Reading: {demo_file}")
df_demographics = pd.read_csv(path_demo)

# Clean and strip column names to ensure perfect matching mechanics
df_country_md.columns = df_country_md.columns.str.strip()
df_demographics.columns = df_demographics.columns.str.strip()

print(f"-> Country Index (Modified) Shape: {df_country_md.shape}")
print(f"-> Demographics Baseline Shape:   {df_demographics.shape}\n")

# ==========================================
# 3. PERFORM INNER JOIN USING 'location_key'
# ==========================================
print("Merging datasets on matching 'location_key' codes...")

df_merged_profile = pd.merge(
    df_country_md,
    df_demographics,
    on='location_key',
    how='inner'
)

print(f"-> Integrated Profile Shape:      {df_merged_profile.shape}")

# ==========================================
# 4. EXPORT INTEGRATED DATA TO PHYSICAL CSV
# ==========================================
print(f"Writing integrated file to Drive: {output_file}")

# index=False ensures no unnecessary, unnamed tracking column is created in your file
df_merged_profile.to_csv(path_output, index=False)

print("=" * 65)
print("✅ Success! Integrated demographics file created and saved.")
print(f"Target Destination: {path_output}")
print("=" * 65)

# ==========================================
# 5. INTEGRITY VALIDATION PREVIEW
# ==========================================
print("\n--- FIRST 10 ROWS OF THE MERGED DEMOGRAPHICS PROFILE ---")
pd.set_option('display.max_columns', 12)
print(df_merged_profile.head(10))

# =======================================================================
# Merge "Country_Ind_md.csv" and "health.csv" per Location_key
# =======================================================================

import os
import pandas as pd

# ==========================================
# 1. DEFINE SHARED WORKSPACE PATHS
# ==========================================
data_dir = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'

country_file = "Country_Ind_md.csv"
health_file = "health.csv"
output_file = "health_Ind_md.csv"

path_country = os.path.join(data_dir, country_file)
path_health = os.path.join(data_dir, health_file)
path_output = os.path.join(data_dir, output_file)

print("Initializing health infrastructure integration pipeline...")

# ==========================================
# 2. UPLOAD & READ BOTH FILES
# ==========================================
if not os.path.exists(path_country) or not os.path.exists(path_health):
    raise FileNotFoundError("❌ Error: Missing source files. Please ensure both 'Country_Ind_md.csv' and 'health.csv' are present in the directory.")

print(f"Reading: {country_file}")
df_country_md = pd.read_csv(path_country)

print(f"Reading: {health_file}")
df_health = pd.read_csv(path_health)

# Clean and strip column names to ensure perfect matching mechanics
df_country_md.columns = df_country_md.columns.str.strip()
df_health.columns = df_health.columns.str.strip()

print(f"-> Country Index (Modified) Shape: {df_country_md.shape}")
print(f"-> Health Baseline Shape:          {df_health.shape}\n")

# ==========================================
# 3. PERFORM INNER JOIN USING 'location_key'
# ==========================================
print("Merging datasets on matching 'location_key' codes...")

df_merged_health = pd.merge(
    df_country_md,
    df_health,
    on='location_key',
    how='inner'
)

print(f"-> Integrated Health Shape:        {df_merged_health.shape}")

# ==========================================
# 4. EXPORT INTEGRATED DATA TO PHYSICAL CSV
# ==========================================
print(f"Writing integrated file to Drive: {output_file}")

# index=False ensures no unnecessary, unnamed tracking column is created in your file
df_merged_health.to_csv(path_output, index=False)

print("=" * 65)
print("✅ Success! Integrated health infrastructure file created and saved.")
print(f"Target Destination: {path_output}")
print("=" * 65)

# ==========================================
# 5. INTEGRITY VALIDATION PREVIEW
# ==========================================
print("\n--- FIRST 10 ROWS OF THE MERGED HEALTH PROFILE ---")
pd.set_option('display.max_columns', 12)
print(df_merged_health.head(10))

# ==================================================
# Update "WHO-COVID-19-global-daily-data.csv"
# ==================================================

# Modify "WHO-COVID-19-global-daily-data.csv" table as follow
# New_cases=0 where field content is null/empty
# New_deaths=0 where field content is null/empty

import os
import pandas as pd

# ==========================================
# 1. DEFINE SHARED WORKSPACE PATHS
# ==========================================
data_dir = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'

input_file = "WHO-COVID-19-global-daily-data.csv"
output_file = "WHO-COVID-19-global-daily-data_md.csv"

path_input = os.path.join(data_dir, input_file)
path_output = os.path.join(data_dir, output_file)

print("Initializing missing value cleanup pipeline...")

# ==========================================
# 2. UPLOAD & READ RAW SOURCE FILE
# ==========================================
if not os.path.exists(path_input):
    raise FileNotFoundError(f"❌ Error: Could not find the source file at {path_input}. Please check the folder connection.")

print(f"Reading: {input_file}")
df_covid = pd.read_csv(path_input)

# Clean up column spaces to guarantee strict target matching
df_covid.columns = df_covid.columns.str.strip()

print(f"-> Base Dataset Shape: {df_covid.shape}")

# ==========================================
# 3. AUDIT & IMPUTE MISSING VALUES WITH 0
# ==========================================
target_cols = ['New_cases', 'New_deaths']

print("\n--- NULL VALUE AUDIT BEFORE CLEANUP ---")
for col in target_cols:
    if col in df_covid.columns:
        null_count = df_covid[col].isnull().sum()
        print(f"Column '{col}': found {null_count} missing values.")
    else:
        print(f"⚠️ Warning: Column '{col}' not found in dataset columns!")

print("\nExecuting data modification (Filling Nulls with 0)...")
# Safely replace all missing values in our target parameters with the actual integer 0
for col in target_cols:
    if col in df_covid.columns:
        df_covid[col] = df_covid[col].fillna(0)

print("\n--- NULL VALUE AUDIT AFTER CLEANUP ---")
for col in target_cols:
    if col in df_covid.columns:
        null_count = df_covid[col].isnull().sum()
        print(f"Column '{col}': found {null_count} missing values.")

# ==========================================
# 4. EXPORT IMMUTABLE CLEANED DATA TO CSV
# ==========================================
print(f"\nWriting modified dataset to Drive: {output_file}")

# index=False drops the default sequential tracking axis from being permanently baked into the file
df_covid.to_csv(path_output, index=False)

print("=" * 70)
print("✅ Success! Modified COVID-19 dataset created and saved securely.")
print(f"Target Destination: {path_output}")
print("=" * 70)

# ==========================================
# 5. INTEGRITY VALIDATION PREVIEW
# ==========================================
print("\n--- FIRST 10 ROWS OF THE MODIFIED TIMELINE PROFILE ---")
pd.set_option('display.max_columns', 12)
print(df_covid.head(10))

# =======================================================================
# Merge "Country_Ind_md.csv" and "vaccination.csv" per Location_key
# =======================================================================

import os
import pandas as pd

# ==========================================
# 1. DEFINE SHARED WORKSPACE PATHS
# ==========================================
data_dir = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'

country_file = "Country_Ind_md.csv"
vaccination_file = "vaccinations.csv"
output_file = "vaccinations_Ind_md.csv"

path_country = os.path.join(data_dir, country_file)
path_vac = os.path.join(data_dir, vaccination_file)
path_output = os.path.join(data_dir, output_file)

print("Initializing vaccination timeline integration pipeline...")

# ==========================================
# 2. UPLOAD & READ BOTH FILES
# ==========================================
if not os.path.exists(path_country) or not os.path.exists(path_vac):
    raise FileNotFoundError("❌ Error: Missing source files. Please ensure both 'Country_Ind_md.csv' and 'vaccinations.csv' are present in the directory.")

print(f"Reading: {country_file}")
df_country_md = pd.read_csv(path_country)

print(f"Reading: {vaccination_file}")
df_vac = pd.read_csv(path_vac)

# Clean and strip column names to ensure perfect matching mechanics
df_country_md.columns = df_country_md.columns.str.strip()
df_vac.columns = df_vac.columns.str.strip()

print(f"-> Country Index (Modified) Shape: {df_country_md.shape}")
print(f"-> Vaccinations Baseline Shape:    {df_vac.shape}\n")

# ==========================================
# 3. PERFORM INNER JOIN USING 'location_key'
# ==========================================
print("Merging datasets on matching 'location_key' codes...")

df_merged_vac = pd.merge(
    df_country_md,
    df_vac,
    on='location_key',
    how='inner'
)

print(f"-> Integrated Vaccination Shape:   {df_merged_vac.shape}")

# ==========================================
# 4. EXPORT INTEGRATED DATA TO PHYSICAL CSV
# ==========================================
print(f"Writing integrated file to Drive: {output_file}")

# index=False ensures no unnecessary, unnamed tracking column is created in your file
df_merged_vac.to_csv(path_output, index=False)

print("=" * 65)
print("✅ Success! Integrated vaccination timeline file created and saved.")
print(f"Target Destination: {path_output}")
print("=" * 65)

# ==========================================
# 5. INTEGRITY VALIDATION PREVIEW
# ==========================================
print("\n--- FIRST 10 ROWS OF THE MERGED VACCINATION PROFILE ---")
pd.set_option('display.max_columns', 12)
print(df_merged_vac.head(10))

# =======================================================================
# Merge "Country_Ind_md.csv" and "epidemiology.csv" per Location_key
# =======================================================================

import os
import pandas as pd

# ==========================================
# 1. DEFINE SHARED WORKSPACE PATHS
# ==========================================
data_dir = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'

country_file = "Country_Ind_md.csv"
epi_file = "epidemiology.csv"
output_file = "epidemiology_Ind_md.csv"

path_country = os.path.join(data_dir, country_file)
path_epi = os.path.join(data_dir, epi_file)
path_output = os.path.join(data_dir, output_file)

print("Initializing epidemiology timeline integration pipeline...")

# ==========================================
# 2. UPLOAD & READ BOTH FILES
# ==========================================
if not os.path.exists(path_country) or not os.path.exists(path_epi):
    raise FileNotFoundError("❌ Error: Missing source files. Please ensure both 'Country_Ind_md.csv' and 'epidemiology.csv' are present in the directory.")

print(f"Reading: {country_file}")
df_country_md = pd.read_csv(path_country)

print(f"Reading: {epi_file}")
df_epi = pd.read_csv(path_epi)

# Clean and strip column names to ensure perfect matching mechanics
df_country_md.columns = df_country_md.columns.str.strip()
df_epi.columns = df_epi.columns.str.strip()

print(f"-> Country Index (Modified) Shape: {df_country_md.shape}")
print(f"-> Epidemiology Baseline Shape:    {df_epi.shape}\n")

# ==========================================
# 3. PERFORM INNER JOIN USING 'location_key'
# ==========================================
print("Merging datasets on matching 'location_key' codes...")

df_merged_epi = pd.merge(
    df_country_md,
    df_epi,
    on='location_key',
    how='inner'
)

print(f"-> Integrated Epidemiology Shape:   {df_merged_epi.shape}")

# ==========================================
# 4. EXPORT INTEGRATED DATA TO PHYSICAL CSV
# ==========================================
print(f"Writing integrated file to Drive: {output_file}")

# index=False ensures no unnecessary, unnamed tracking column is created in your file
df_merged_epi.to_csv(path_output, index=False)

print("=" * 65)
print("✅ Success! Integrated epidemiology timeline file created and saved.")
print(f"Target Destination: {path_output}")
print("=" * 65)

# ==========================================
# 5. INTEGRITY VALIDATION PREVIEW
# ==========================================
print("\n--- FIRST 10 ROWS OF THE MERGED EPIDEMIOLOGY PROFILE ---")
pd.set_option('display.max_columns', 12)
print(df_merged_epi.head(10))

# =======================================================================
# Validate "2021-GHS-Index-April-2022.csv" has no null values inside
# =======================================================================

import os
import pandas as pd

# ==========================================
# 1. DEFINE SHARED WORKSPACE PATH
# ==========================================
data_dir = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'
input_file = "2021-GHS-Index-April-2022.csv"
path_input = os.path.join(data_dir, input_file)

print("Initializing GHS Index null value audit pipeline...")

# ==========================================
# 2. UPLOAD & READ RAW SOURCE FILE
# ==========================================
if not os.path.exists(path_input):
    raise FileNotFoundError(f"❌ Error: Could not find the file at {path_input}. Please verify your Google Drive connection.")

df_ghs = pd.read_csv(path_input)
print(f"-> Dataset successfully loaded. Shape: {df_ghs.shape}\n")

# ==========================================
# 3. COMPUTE AND EVALUATE NULL FIELDS
# ==========================================
# Calculate the total number of missing values across every field
null_counts = df_ghs.isnull().sum()
total_nulls = null_counts.sum()

print("=" * 65)
print("                  NULL VALUE AUDIT REPORT")
print("=" * 65)

# Check if any missing values exist in the entire matrix
if total_nulls > 0:
    print(f"⚠️ Audit State: Found a total of {total_nulls} null/empty cells in the table.\n")
    print("Columns containing missing values and their respective counts:")

    # Isolate and display only fields that contain 1 or more missing values
    columns_with_nulls = null_counts[null_counts > 0]
    print(columns_with_nulls)
else:
    # Print the exact required confirmation message if no nulls are found
    print("File is ready to be used - no null/empty value inside")

print("=" * 65)

# =======================================================================
#Merge "2021-GHS-Index-April-2022.csv" and "Country_Ind_md.csv"
# =======================================================================

# Country_name is the field combine between the two tables by inner join

import os
import pandas as pd

# ==========================================
# 1. DEFINE SHARED WORKSPACE PATHS
# ==========================================
data_dir = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'

country_file = "Country_Ind_md.csv"
ghs_file = "2021-GHS-Index-April-2022.csv"
output_file = "2021-GHS-Index-April-2022_Ind_md.csv"

path_country = os.path.join(data_dir, country_file)
path_ghs = os.path.join(data_dir, ghs_file)
path_output = os.path.join(data_dir, output_file)

print("Initializing GHS Index integration pipeline...")

# ==========================================
# 2. UPLOAD & READ BOTH FILES
# ==========================================
if not os.path.exists(path_country) or not os.path.exists(path_ghs):
    raise FileNotFoundError("❌ Error: Missing source files. Please ensure both 'Country_Ind_md.csv' and '2021-GHS-Index-April-2022.csv' are present in the directory.")

print(f"Reading: {country_file}")
df_country_md = pd.read_csv(path_country)

print(f"Reading: {ghs_file}")
df_ghs = pd.read_csv(path_ghs)

# Clean and strip column names to ensure perfect matching mechanics
df_country_md.columns = df_country_md.columns.str.strip()
df_ghs.columns = df_ghs.columns.str.strip()

print(f"-> Country Index (Modified) Shape: {df_country_md.shape}")
print(f"-> GHS Index Baseline Shape:       {df_ghs.shape}\n")

# ==========================================
# 3. STANDARDIZE & PERFORM INNER JOIN
# ==========================================
print("Standardizing match identifiers and merging datasets...")

# Ensure casing and trailing spaces don't interfere with the text match
df_country_md['match_country'] = df_country_md['country_name'].astype(str).str.strip().str.lower()
df_ghs['match_country'] = df_ghs['Country'].astype(str).str.strip().str.lower()

df_merged_ghs = pd.merge(
    df_country_md,
    df_ghs,
    on='match_country',
    how='inner'
)

# Clean up the temporary alignment columns used for joining
df_merged_ghs = df_merged_ghs.drop(columns=['match_country'])

print(f"-> Integrated GHS Index Shape:     {df_merged_ghs.shape}")

# ==========================================
# 4. EXPORT INTEGRATED DATA TO PHYSICAL CSV
# ==========================================
print(f"Writing integrated file to Drive: {output_file}")

# index=False ensures no unnecessary, unnamed tracking column is created in your file
df_merged_ghs.to_csv(path_output, index=False)

print("=" * 65)
print("✅ Success! Integrated GHS Index file created and saved.")
print(f"Target Destination: {path_output}")
print("=" * 65)

# ==========================================
# 5. INTEGRITY VALIDATION PREVIEW
# ==========================================
print("\n--- FIRST 10 ROWS OF THE MERGED GHS PROFILE ---")
pd.set_option('display.max_columns', 12)
print(df_merged_ghs.head(10))

# ==================================================================================
# Merge "2021-GHS-Index-April-2022_Ind_md.csv" and "ict adoption by 100 people.csv"
# ==================================================================================

# Country/Country_name is the field combine between the two tables by inner join
# Before Merge activity both tables are clean and left with records of only Year = 2019 or 2021 and kept in temp tables

import os
import pandas as pd

# ==========================================
# 1. DEFINE SHARED WORKSPACE PATHS
# ==========================================
data_dir = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'

ict_file = "ict adoption by 100 people.csv"
ghs_file = "2021-GHS-Index-April-2022_Ind_md.csv"
output_file = "ICT_GHS_Ind_md.csv"

path_ict = os.path.join(data_dir, ict_file)
path_ghs = os.path.join(data_dir, ghs_file)
path_output = os.path.join(data_dir, output_file)

print("Initializing ICT & GHS Year-Filtered Integration Pipeline...")

# ==========================================
# 2. READ SOURCE DATASETS
# ==========================================
if not os.path.exists(path_ict) or not os.path.exists(path_ghs):
    raise FileNotFoundError("❌ Error: Missing source files. Please ensure both files exist in your Drive directory.")

df_ict_raw = pd.read_csv(path_ict)
df_ghs_raw = pd.read_csv(path_ghs)

# Clean column headers
df_ict_raw.columns = df_ict_raw.columns.str.strip()
df_ghs_raw.columns = df_ghs_raw.columns.str.strip()

print(f"-> Raw ICT Adoption Table Shape:       {df_ict_raw.shape}")
print(f"-> Raw GHS Index Modified Table Shape: {df_ghs_raw.shape}\n")

# Ensure a Year column exists in the GHS table for filtering (adds it if missing, as it represents 2021 data)
if 'Year' not in df_ghs_raw.columns:
    df_ghs_raw['Year'] = 2021

# ==========================================
# 3. FILTER BOTH TABLES FOR YEARS 2019 OR 2021
# ==========================================
print("Filtering rows for Year 2019 or 2021 into temporary tables...")

# Step 1: Filter ICT Table
df_ict_temp = df_ict_raw[df_ict_raw['Year'].isin([2019, 2021])].copy()

# Step 2: Filter GHS Table
df_ghs_temp = df_ghs_raw[df_ghs_raw['Year'].isin([2019, 2021])].copy()

print(f"   - Temp ICT Table Shape (2019/2021): {df_ict_temp.shape}")
print(f"   - Temp GHS Table Shape (2019/2021): {df_ghs_temp.shape}\n")

# ==========================================
# 4. STANDARDIZE KEYS AND MERGE
# ==========================================
print("Standardizing match identifiers and merging data...")

# Determine the country name column in ICT table (handles 'Country' or 'Country Name')
ict_country_col = 'Entity' if 'Entity' in df_ict_temp.columns else 'Country'
ghs_country_col = 'Country' if 'Country' in df_ghs_temp.columns else 'country_name'

# Create standardized lowercase matching columns to safeguard against spacing differences
df_ict_temp['match_country'] = df_ict_temp[ict_country_col].astype(str).str.strip().str.lower()
df_ghs_temp['match_country'] = df_ghs_temp[ghs_country_col].astype(str).str.strip().str.lower()

# Inner join on BOTH Country and Year matching criteria
df_merged = pd.merge(
    df_ict_temp,
    df_ghs_temp,
    on=['match_country', 'Year'],
    how='inner'
)

# Remove the temporary match keys
df_merged = df_merged.drop(columns=['match_country'])

print(f"-> Final Filtered & Merged Table Shape: {df_merged.shape}")

# ==========================================
# 5. EXPORT INTEGRATED DATA TO PHYSICAL CSV
# ==========================================
print(f"Writing output file to Drive: {output_file}")
df_merged.to_csv(path_output, index=False)

print("=" * 75)
print("✅ Success! Filtered merge completed successfully.")
print(f"Target Destination: {path_output}")
print("=" * 75)

# ==========================================
# 6. INTEGRITY VALIDATION PREVIEW
# ==========================================
print("\n--- FIRST 10 ROWS OF THE MERGED DATASET ---")
pd.set_option('display.max_columns', None)
print(df_merged.head(10))

"""## Descriptive Statistic on new Base Dataset
Here we are running Descriptive statistic on each new given table of the dataset using describe() pandas function.

**In Pandas, describe()** is a built-in function that automatically computes a comprehensive summary of descriptive statistics for a DataFrame. Instead of writing separate code for the mean, median, min, max, and standard deviation, calling this single function calculates them all at once.

***By default***, it analyzes numerical columns and provides:
*   **count**: Number of non-missing (non-NaN) values.
*   **mean**: The arithmetic average.
*   **std**: Standard deviation (measures how spread out the data is).
*   **min**: The lowest value in the column.
*   **5%, 50%, 75%**: The percentiles (where 50% is the Median).
*   **max**: The highest value in the column.

To capture categorical (text) columns as well, we can use df.describe(include='all'), which adds metrics like unique (count of distinct values) and top (the most frequent value).
"""

# ==================================================
# 1. "מאחר וזה קובץ מקשר לא נדרש סטטוסטיקות עבורו" Descriptive Statistic - "Country_Ind_md.csv"
# ==================================================

import os
import pandas as pd

# ==========================================
# 1. DEFINE SHARED WORKSPACE PATHS
# ==========================================
data_dir = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'
target_file = "Country_Ind_md.csv"
path_target = os.path.join(data_dir, target_file)

print(f"Loading {target_file} for Descriptive Analysis...")

# ==========================================
# 2. READ TARGET DATASET
# ==========================================
if not os.path.exists(path_target):
    raise FileNotFoundError(f"❌ Error: Could not find '{target_file}' in the directory.")

df = pd.read_csv(path_target)

# ==========================================
# 3. RUN UNIFIED DESCRIPTIVE STATISTICS
# ==========================================
print("=" * 75)
print(f"       DESCRIPTIVE STATISTICS SUMMARY: {target_file}         ")
print("=" * 75)

# Setting options so Colab doesn't truncate the columns visually in the output window
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

# include='all' forces Pandas to combine text and numeric summaries into a single unified table
unified_summary = df.describe(include='all')

print(unified_summary)
print("=" * 75)

"""
This table contains static country healthcare metrics and pre-existing medical vulnerabilities (like life expectancy, smoking prevalence, diabetes prevalence, and physician counts).
These features will act as your main baseline risk predictors.
"""

# ==================================================
# 2. Descriptive Statistic - health_Ind_md.csv
# ==================================================

import os
import pandas as pd

# ==========================================
# 1. DEFINE SHARED WORKSPACE PATHS
# ==========================================
data_dir = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'
target_file = "health_Ind_md.csv"
path_target = os.path.join(data_dir, target_file)

print(f"Loading {target_file} for Descriptive Analysis...")

# ==========================================
# 2. READ TARGET DATASET
# ==========================================
if not os.path.exists(path_target):
    raise FileNotFoundError(f"❌ Error: Could not find '{target_file}' in the directory.")

df = pd.read_csv(path_target)

# ==========================================
# 3. RUN UNIFIED DESCRIPTIVE STATISTICS
# ==========================================
print("=" * 75)
print(f"       DESCRIPTIVE STATISTICS SUMMARY: {target_file}         ")
print("=" * 75)

# Configuring display variables so Colab renders the entire width of the summary table
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

# include='all' builds the comprehensive statistics profile for both numeric and text categories
unified_summary = df.describe(include='all')

print(unified_summary)
print("=" * 75)

"""
This table contains static structural population distributions across age brackets, density metrics, and development index indicators, which are highly critical for evaluating regional vulnerabilities.
"""

# ==================================================
# 3. Descriptive Statistic - demographics_Ind_md.csv
# ==================================================

import os
import pandas as pd

# ==========================================
# 1. DEFINE SHARED WORKSPACE PATHS
# ==========================================
data_dir = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'
target_file = "demographics_Ind_md.csv"
path_target = os.path.join(data_dir, target_file)

print(f"Loading {target_file} for Descriptive Analysis...")

# ==========================================
# 2. READ TARGET DATASET
# ==========================================
if not os.path.exists(path_target):
    raise FileNotFoundError(f"❌ Error: Could not find '{target_file}' in the directory.")

df = pd.read_csv(path_target)

# ==========================================
# 3. RUN UNIFIED DESCRIPTIVE STATISTICS
# ==========================================
print("=" * 75)
print(f"       DESCRIPTIVE STATISTICS SUMMARY: {target_file}         ")
print("=" * 75)

# Configuring options so Colab displays all data columns without text wrapping truncation
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

# include='all' forces a single matrix showing categorical distributions alongside numerical metrics
unified_summary = df.describe(include='all')

print(unified_summary)
print("=" * 75)

"""
This table contains the core global daily tracking indicators for cases and deaths reported directly to the WHO.
"""

# ===============================================================
# 4. Descriptive Statistic - WHO-COVID-19-global-daily-data_md.csv
# ===============================================================

import os
import pandas as pd

# ==========================================
# 1. DEFINE SHARED WORKSPACE PATHS
# ==========================================
data_dir = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'
target_file = "WHO-COVID-19-global-daily-data_md.csv"
path_target = os.path.join(data_dir, target_file)

print(f"Loading {target_file} for Descriptive Analysis...")

# ==========================================
# 2. READ TARGET DATASET
# ==========================================
if not os.path.exists(path_target):
    raise FileNotFoundError(f"❌ Error: Could not find '{target_file}' in the directory.")

df = pd.read_csv(path_target)

# ==========================================
# 3. RUN UNIFIED DESCRIPTIVE STATISTICS
# ==========================================
print("=" * 75)
print(f"       DESCRIPTIVE STATISTICS SUMMARY: {target_file}         ")
print("=" * 75)

# Configuring display variables so Colab renders the entire width of the summary table
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

# include='all' builds the comprehensive statistics profile for both numeric and text categories
unified_summary = df.describe(include='all')

print(unified_summary)
print("=" * 75)

"""
This dataset tracks a nation's digital infrastructure capacity over time (mobile subscriptions, internet penetration, etc.), which will allow us to assess how well
technology aided communication and rapid response during the crisis.
"""

# ==================================================
# 5. Descriptive Statistic - ict adoption by 100 people.csv
# ==================================================

import os
import pandas as pd

# ==========================================
# 1. DEFINE SHARED WORKSPACE PATHS
# ==========================================
data_dir = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'data_dir = './data/'
target_file = "ict adoption by 100 people.csv"
path_target = os.path.join(data_dir, target_file)

print(f"Loading {target_file} for Descriptive Analysis...")

# ==========================================
# 2. READ TARGET DATASET
# ==========================================
if not os.path.exists(path_target):
    raise FileNotFoundError(f"❌ Error: Could not find '{target_file}' in the directory.")

df = pd.read_csv(path_target)

# ==========================================
# 3. RUN UNIFIED DESCRIPTIVE STATISTICS
# ==========================================
print("=" * 75)
print(f"       DESCRIPTIVE STATISTICS SUMMARY: {target_file}         ")
print("=" * 75)

# Configuring display variables so Colab renders the entire width of the summary table
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

# include='all' builds the comprehensive statistics profile for both numeric and text categories
unified_summary = df.describe(include='all')

print(unified_summary)
print("=" * 75)

"""
This table contains the Global Health Security Index dimensions, evaluating countries across critical health security pillars such as early detection, rapid response, compliance
with international norms, and risk environments.
"""

# ==================================================
# 6. Descriptive Statistic - 2021-GHS-Index-April-2022_Ind_md.csv
# ==================================================

import os
import pandas as pd

# ==========================================
# 1. DEFINE SHARED WORKSPACE PATHS
# ==========================================
data_dir = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'
target_file = "2021-GHS-Index-April-2022_Ind_md.csv"
path_target = os.path.join(data_dir, target_file)

print(f"Loading {target_file} for Descriptive Analysis...")

# ==========================================
# 2. READ TARGET DATASET
# ==========================================
if not os.path.exists(path_target):
    raise FileNotFoundError(f"❌ Error: Could not find '{target_file}' in the directory.")

df = pd.read_csv(path_target)

# ==========================================
# 3. RUN UNIFIED DESCRIPTIVE STATISTICS
# ==========================================
print("=" * 75)
print(f"       DESCRIPTIVE STATISTICS SUMMARY: {target_file}         ")
print("=" * 75)

# Configuring display variables so Colab renders the entire width of the summary table
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

# include='all' builds the comprehensive statistics profile for both numeric and text categories
unified_summary = df.describe(include='all')

print(unified_summary)
print("=" * 75)

"""
This is one of the heavy time-series tracking files, containing day-by-day records of confirmed cases, active cases, recoveries, and mortality figures grouped by geographic location identifiers.
"""

# ==================================================
# 7. Descriptive Statistic - epidemiology_Ind_md.csv
# ==================================================

import os
import pandas as pd

# ==========================================
# 1. DEFINE SHARED WORKSPACE PATHS
# ==========================================
data_dir = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'
target_file = "epidemiology_Ind_md.csv"
path_target = os.path.join(data_dir, target_file)

print(f"Loading {target_file} for Descriptive Analysis...")

# ==========================================
# 2. READ TARGET DATASET
# ==========================================
if not os.path.exists(path_target):
    raise FileNotFoundError(f"❌ Error: Could not find '{target_file}' in the directory.")

df = pd.read_csv(path_target)

# ==========================================
# 3. RUN UNIFIED DESCRIPTIVE STATISTICS
# ==========================================
print("=" * 75)
print(f"       DESCRIPTIVE STATISTICS SUMMARY: {target_file}         ")
print("=" * 75)

# Configuring display variables so Colab renders the entire width of the summary table
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

# include='all' builds the comprehensive statistics profile for both numeric and text categories
unified_summary = df.describe(include='all')

print(unified_summary)
print("=" * 75)

"""
This table contains daily metrics on vaccine doses administered, cumulative rollout volumes, and
the count of persons who have completed their vaccination schedule per region.
"""

# ==================================================
# 8. Descriptive Statistic - vaccinations_Ind_md.csv
# ==================================================

import os
import pandas as pd

# ==========================================
# 1. DEFINE SHARED WORKSPACE PATHS
# ==========================================
data_dir = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'
target_file = "vaccinations_Ind_md.csv"
path_target = os.path.join(data_dir, target_file)

print(f"Loading {target_file} for Descriptive Analysis...")

# ==========================================
# 2. READ TARGET DATASET
# ==========================================
if not os.path.exists(path_target):
    raise FileNotFoundError(f"❌ Error: Could not find '{target_file}' in the directory.")

df = pd.read_csv(path_target)

# ==========================================
# 3. RUN UNIFIED DESCRIPTIVE STATISTICS
# ==========================================
print("=" * 75)
print(f"       DESCRIPTIVE STATISTICS SUMMARY: {target_file}         ")
print("=" * 75)

# Configuring display variables so Colab renders the entire width of the summary table
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

# include='all' builds the comprehensive statistics profile for both numeric and text categories
unified_summary = df.describe(include='all')

print(unified_summary)
print("=" * 75)

"""
This table is the output results of merge activity between ict adoption by 100 people.csv and 2021-GHS-Index-April-2022_Ind_md.csv table
where first each of those tables were cleaned and remains with records of Year=2019 or 2021 only
 """

# ==================================================
# 8. Descriptive Statistic - ICT_GHS_Ind_md.csv
# ==================================================

import os
import pandas as pd

# ==========================================
# 1. DEFINE SHARED WORKSPACE PATHS
# ==========================================
data_dir = '/content/drive/MyDrive/DS_IsTheWorldReadyForTheNextPandemic/DATASET TO USE/'
target_file = "ICT_GHS_Ind_md.csv"
path_target = os.path.join(data_dir, target_file)

print(f"Loading {target_file} for Descriptive Analysis...")

# ==========================================
# 2. READ TARGET DATASET
# ==========================================
if not os.path.exists(path_target):
    raise FileNotFoundError(f"❌ Error: Could not find '{target_file}' in the directory.")

df = pd.read_csv(path_target)

# ==========================================
# 3. RUN UNIFIED DESCRIPTIVE STATISTICS
# ==========================================
print("=" * 75)
print(f"       DESCRIPTIVE STATISTICS SUMMARY: {target_file}         ")
print("=" * 75)

# Configuring display variables so Colab renders the entire width of the summary table
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

# include='all' builds the comprehensive statistics profile for both numeric and text categories
unified_summary = df.describe(include='all')

print(unified_summary)
print("=" * 75)
